version: '3.8'

services:
  mixpost:
    image: inovector/mixpost:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "80:80"
    volumes:
      - storage:/var/www/html/storage/app
      - logs:/var/www/html/storage/logs
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql:/var/lib/mysql

  redis:
    image: redis:latest
    restart: unless-stopped

volumes:
  mysql:
  storage:
  logs:
